import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs';
import { startMock } from '../../packages/zero-core/mock-supabase.mjs';
import { buildZero } from './build.mjs';
const mock = await startMock({ ttlSec: 3600 });
const OUT='dist-dbg';
await buildZero({url:mock.url,anonKey:'anon-key',outdir:OUT,single:false});
const srv=http.createServer((q,r)=>{const f=OUT+'/'+(q.url.split('?')[0]==='/'?'index.html':q.url.slice(1));if(!fs.existsSync(f)){r.writeHead(404);return r.end()}r.writeHead(200,{'Content-Type':f.endsWith('.js')?'text/javascript':'text/html'});r.end(fs.readFileSync(f))});
await new Promise(r=>srv.listen(0,'127.0.0.1',r));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const p=await b.newPage({viewport:{width:430,height:900}});
p.on('pageerror',e=>console.log('PAGEERROR', e.message));
p.on('console',m=>{ if(m.type()==='error') console.log('CONSOLE', m.text()); });
await p.goto(`http://127.0.0.1:${srv.address().port}/`);
await p.waitForTimeout(700);
await p.fill('input[placeholder="email"]','dbg@example.com');
await p.fill('input[placeholder="password"]','pw12345');
await p.click('button:has-text("create account")');
await p.waitForTimeout(800);
await p.click('button:has-text("Targets+")');
await p.waitForTimeout(600);
const t = await p.textContent('body');
console.log('HAS Loads from Bench:', t.includes('Loads from Bench'));
console.log('HAS Targets heading:', t.includes('Target'));
console.log(t.slice(0,400).replace(/\s+/g,' '));
await b.close(); srv.close();
